### ISSUE TITLE
Question about frame-to-instance implemenation

### ISSUE THREAD

**Issue by Gmbition** [amazon-science/semimtr-text-recognition#11]
Hi, thanks for your great work！
When I run the code, I have a problem in the following line:
https://github.com/amazon-science/semimtr-text-recognition/blob/d4921a3e36f4ba424e79cf64100515f3bc9c9a0d/semimtr/modules/seqclr_proj.py#L59
It seems like this implementation performs row-wise avgpooling which concats each row and then performs avgpooling. However, in the original paper, column-wise avgpooling is performed, which should be:
`features = features.permute(0, 3, 2, 1).flatten(1, 2)`
I have no idea whether this difference is matter. 
Thank you~

**Comment by aaberdam** [comment]
Hi,

Thank you for the interest in our work.

In SemiMTR, we used a 2D feature map and therefore the instance-mapping is applied on `H*W`. In SeqCLR paper, the visual backbone consists of ResNet and a pooling layer that outputs a 1D feature map `(N, W, E)`. As you said, in SeqCLR the instance mapping function averages columns of features.
In other words, your instance-mapping function is dependent with your visual backbone, and if you use a 2D feature map then you need to use a 2D instance-mapping function.

I hope you find this helpful, if not please reach out again.
Aviad
