### ISSUE TITLE
About EMA

### ISSUE THREAD

**Issue by YuNie24** [amazon-science/semimtr-text-recognition#13]
Didn't you use EMA(exponential moving average) between teacher & student model?
I found related code (https://github.com/amazon-science/semimtr-text-recognition/blob/main/semimtr/modules/model_fusion_teacher_student_ema.py) but there is any usage.

Thanks You for nice repository!!

**Comment by aaberdam** [comment]
Hi, 

Thank you for your interest in our work.

To enable EMA, set `ema: True` in the configuration file found at this link:
https://github.com/amazon-science/semimtr-text-recognition/blob/d4921a3e36f4ba424e79cf64100515f3bc9c9a0d/configs/semimtr_finetune.yaml#L86
This will cause the program to use the script `model_fusion_teacher_student_ema.py`.

By default, the teacher gradients are stopped, but if you wish to change this, you can do so also in this configuration.

If you have any more questions, please let me know.
Aviad

**Comment by YuNie24** [comment]
Thank you for reply :)

but still have some questions.

Would you explain more on how "model_fusion_teacher_student_ema.py" is called?

According to my test of your SemiMTR finetune scripts, "ConsistencyRegularizationFusionModel" model has about 36M trainable parameter and students and teacher use the same model parameters.

However, when using EMA, it seems that the parameters should be doubled because structure have to have a separate ABINetIterModel on student and teacher.

I set ema: True in the configuration file(semimtr_finetune.yaml), but trainable parameter has still 36M and looks not using TeacherStudentFusionEMA.

**Comment by YuNie24** [comment]
Ah, I just checked another config line.

> https://github.com/amazon-science/semimtr-text-recognition/blob/d4921a3e36f4ba424e79cf64100515f3bc9c9a0d/configs/semimtr_finetune.yaml#L56

and it looks like it should be `name: semimtr.modules.model_fusion_teacher_student_ema.TeacherStudentFusionEMA`
instead of `semimtr.modules.model_fusion_consistency_regularization.ConsistencyRegularizationFusionModel`

then TeacherStudentFusionEMA and ConsistencyRegularizationFusionModel cannot be executed simultaneously.
is it right ?
